version: '3'

services:
  proxy:
    build:
      context: ./src/proxy
      dockerfile: Dockerfile
    container_name: proxy
    networks:
      - envoymesh
    ports:
      - "8080:8080"
      - "8081:8081"

  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    container_name: server
    # DOCKER : ENVOY - FRONT PROXY
    # https://www.bogotobogo.com/DevOps/Docker/Docker-Envoy-Front-Proxy.php
    networks:
      envoymesh:
        aliases:
          - server
    ports:
      - "9090:9090"

  greetserver:
    build:
      context: ./src/greetserver
      dockerfile: Dockerfile
    container_name: greetserver
    networks:
      envoymesh:
        aliases:
          - greetserver
    ports:
      - "9091:9091"

networks:
  envoymesh: {}
