version: '3'

services:
  proxy:
    build:
      context: ./src/proxy
      dockerfile: Dockerfile
    container_name: proxy
    networks:
      envoymesh:
        aliases:
          - proxy
    ports:
      - "8080:8080"

  greetserver:
    build:
      context: ./src/greetserver
      dockerfile: Dockerfile
    container_name: greetserver
    networks:
      envoymesh:
        aliases:
          - greetserver
    ports:
      - "9091:9091"

  greetclient:
    build:
      context: ./src/greetclient
      dockerfile: Dockerfile
    environment:
      - GREET_CLIENT_NAME=hello 

  ## これより下は hello worldのみ
  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    container_name: server
    # DOCKER : ENVOY - FRONT PROXY
    # https://www.bogotobogo.com/DevOps/Docker/Docker-Envoy-Front-Proxy.php
    networks:
      envoymesh:
        aliases:
          - server
    ports:
      - "9090:9090"

  rust:
    build:
      context: ./src/rust
      dockerfile: Dockerfile

networks:
  envoymesh: {}
